name: Pull Request (terraform validate & plan)

on:
  - pull_request

env:
  APP_NAME: comment-on-pr-action

jobs:
  validate:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Update PR and add comment for terrform plan
        uses: Waschnick/comment-on-pr-action@v1
        with:
          filename: .github/github-pull-request-template.md
